[package]
name = "shiplift-macro"
version = "0.1.0"
authors = ["Wojciech Kępka <wojtek.kepka@protonmail.com>"]
edition = "2018"

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"

[lib]
proc_macro = true

